project:
  type: website
  # output-dir: /Users/guhl/Documents/GitHub/open-lx/essais/publx/001
  output-dir: ../../../q/publx/001
website:
  title: "003"
  navbar:
    left:
      - href: https://esteeschwarz.github.io/open-lx/posts/g-mcculloch
        text: INDEX
    right:
      - snc.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3

execute: 
  freeze: auto

