project:
  type: website
  output-dir: ../../../../q/lx-public/HA/DCL/pages
params:
  reload: false
website:
  navbar:
    left:
    - href: ../../../../../linguistics/dcl-pr
      text: '`<i class="weui--back2-outlined"></i>`{=html}'
    - href: index.qmd
      text: index
    - text: work
      menu:
      - workflow.qmd
      - mermaids.qmd
    - text: drafts
      menu:
      - href: sample-A.html
        text: draft A
      - href: sample-C.html
        text: draft C
    right:
    - href: snc.qmd
    - href: https://github.com/esteeschwarz/SPUND-LX/tree/main/lx-public/HA/DCL/pages
      icon: github
format:
  html:
    theme: cosmo
    monofont: Menlo
    toc: true
    toc-depth: 3
    include-in-header:
      text: |
        <!-- HTML simply prints the inner text -->
        <!-- 16482.snc -->
        <script type="application/latex">
        \newcommand{\he}[1]{#1}
        </script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
        <link rel="stylesheet" href="https://esteeschwarz.github.io/DC-LX/assets/css/icons.css">
editor: source
execute:
  freeze: auto
