format:
  pdf:
    #latex_engine: pdflatex  # default
    fig-pos: "H" # Forces images to appear exactly where they are included
    # mainfont: Georgia
    # mainfont: 'TeX Gyre Termes'
    #mainfont: 'Computer Modern Roman'
    font-size: 12
    #cite-method: biblatex
    colorlinks: true
    header-includes: |
      \usepackage[margin=1in]{geometry}
      \usepackage{fvextra}
      \fvset{breaklines=true, breakanywhere=true}
  html:
    theme:
      - cosmo #litera
      - brand
    #mainfont: Courier
    monofont: Menlo
    #font: Courier
    css: styles.css
    toc: true
