project:
  type: website
  output-dir: ../../../q/sebald/001
params:
    reload: false

website:
  title: "010"
  navbar:
    left:
      - href: ../../../
        text: '<img src="../../../images/backward.end.alt.svg" style="height:1em; vertical-align:-0.1em;">'
      - about.qmd
      - raw.qmd
      - samling.qmd
    right:
      - href: stschwarz-sebald.pdf
        text: pdf
      - snc.qmd
      - href: https://github.com/esteeschwarz/SPUND-LX/tree/main/szondi/docufiction/wg-sebald
        icon: github
  #base-url: /q/ this doesnt wk

format:
  html:
    theme:
      - cosmo #litera
      - brand
    #mainfont: Courier
    monofont: Menlo
    #font: Courier
    css: styles.css
    toc: true

editor: source

execute:
  freeze: auto