project:
  type: website
  output-dir: ../../../q/buechner-a
website:
  title: '006'
  navbar:
    left:
    - href: https://esteeschwarz.github.io/open-lx/posts/buechner-a
      text: INDEX
    - qa.qmd
    right:
    - snc.qmd
    - href: https://github.com/esteeschwarz/SPUND-LX/tree/main/szondi/buechner
      icon: github
format:
  html:
    theme:
    - cosmo
    - brand
    css: styles.css
    toc: true
    toc-depth: 3
execute:
  freeze: auto
