project:
  type: website
  output-dir: ../../../q/buechner-a
  pre-render: "create-slides.R"
website:
  title: '006'
  navbar:
    left:
    - href: ../../
      text: '<img src="backward.end.alt.svg" style="height:1em; vertical-align:-0.1em;">'
    - slides.qmd
    right:
    - snc.qmd
    - href: https://github.com/esteeschwarz/SPUND-LX/tree/main/szondi/buechner
      icon: github
format:
  html:
    theme:
    - cosmo
    - brand
    css: styles.css
    toc: true
    toc-depth: 3
execute:
  freeze: auto
